POST http://mnsstrap.ddns.net:3001/setalldata/client3 HTTP/1.1
content-type: application/json

{
    "battery":"0",
    "humidity":"0",
    "temprature": "40",
    "ServoStatus":"1",
    "timer": "10"
}
